document.querySelectorAll('[data-voice]').forEach(button=>{button.dataset.bound='true';button.addEventListener('click',()=>{button.textContent=button.textContent.includes('Start')?'Stop voice':'F2 / Start voice';button.classList.toggle('recording');});});
document.querySelectorAll('[data-filter]').forEach(input=>input.addEventListener('input',event=>{const query=event.target.value.toLowerCase();document.querySelectorAll('[data-row]').forEach(row=>{row.hidden=query&&!row.textContent.toLowerCase().includes(query);});}));
const orderPreviewPath=location.pathname.includes('/resources/')?'order-preview.html':'resources/order-preview.html';
const resourceNav=document.querySelector('.nav');
const commandSymbol=resourceNav?.querySelector('a[href="../index.html"] .nav-symbol, a[href="../index.html"] b');
if(commandSymbol)commandSymbol.textContent='⌂';
const tripsLabel=resourceNav?.querySelector('a[href="trips.html"] span');
if(tripsLabel)tripsLabel.textContent='Trips în desfășurare';
if(resourceNav){if(!resourceNav.querySelector('a[href="bucket.html"]')){const bucketLink=document.createElement('a');bucketLink.href='bucket.html';bucketLink.innerHTML='<b>B</b><span>The Bucket List</span>';resourceNav.appendChild(bucketLink);}if(!resourceNav.querySelector('a[href="calendar.html"]')){const calendarLink=document.createElement('a');calendarLink.href='calendar.html';calendarLink.innerHTML='<b>C</b><span>Calendar</span>';resourceNav.appendChild(calendarLink);}const menuOrder=['../index.html','calendar.html','opportunities.html','trips.html','bucket.html','fleet.html','finance.html','advisor.html'];menuOrder.forEach(path=>{const link=resourceNav.querySelector(`a[href="${path}"]`);if(link)resourceNav.appendChild(link);});const opportunitiesLink=resourceNav.querySelector('a[href="opportunities.html"]');if(opportunitiesLink)opportunitiesLink.classList.add('nav-divider');const bucketLink=resourceNav.querySelector('a[href="bucket.html"]');if(bucketLink)bucketLink.classList.add('nav-secondary','nav-divider');resourceNav.querySelectorAll('a[href="fleet.html"],a[href="finance.html"],a[href="advisor.html"]').forEach(link=>link.classList.add('nav-secondary'));}
if(resourceNav&&!resourceNav.parentElement.querySelector('.voice-card')){const voiceCard=document.createElement('div');voiceCard.className='voice-card';voiceCard.innerHTML='<strong>Voice capture</strong><p>Draft an opportunity from a short dispatcher note.</p><button class="voice-btn" data-voice>F2 / Start voice</button>';resourceNav.parentElement.appendChild(voiceCard);}
document.querySelectorAll('.voice-card').forEach(card=>{card.style.display='block';const button=card.querySelector('.voice-btn');if(button)button.style.display='block';});
document.querySelectorAll('[data-voice]').forEach(button=>{if(button.dataset.bound)return;button.dataset.bound='true';button.addEventListener('click',()=>{button.textContent=button.textContent.includes('Start')?'Stop voice':'F2 / Start voice';button.classList.toggle('recording');});});
if(!window.tccVoiceShortcut){window.tccVoiceShortcut=true;document.addEventListener('keydown',event=>{if(event.key==='F2'){event.preventDefault();document.querySelector('[data-voice]')?.click();}});}
document.querySelectorAll('.opportunity').forEach(item=>{item.style.cursor='pointer';item.addEventListener('click',()=>{location.href=orderPreviewPath;});});
if(location.pathname.endsWith('/opportunities.html')){document.querySelectorAll('[data-row]').forEach(item=>{item.style.cursor='pointer';item.addEventListener('click',()=>{location.href='order-preview.html';});});}
if(location.pathname.endsWith('/trips.html')){document.querySelectorAll('.table tbody tr').forEach(row=>{row.style.cursor='pointer';row.addEventListener('click',()=>{location.href=`trip-detail.html?trip=${encodeURIComponent(row.cells[0].textContent.trim())}`;});});}
if(location.pathname.endsWith('/fleet.html')){const fleetRows=[['TM-02 / Mercedes Actros','Andrei Marin','Vienna','94%','On route','warn'],['TM-04 / MAN TGX','Elena Stoica','Arad','89%','Ready',''],['TM-05 / Volvo FH','Radu Pavel','Cluj-Napoca','86%','Ready',''],['TM-06 / Scania S','Victor Dinu','Brno','77%','Loading','warn'],['TM-08 / Renault T','Sorin Matei','Budapest','81%','Ready',''],['TM-09 / Iveco S-Way','Adrian Neagu','Timisoara','68%','Inspection','warn'],['TM-10 / Volvo FM','Daniela Rusu','Frankfurt','92%','Ready','']];const fleetBody=document.querySelector('.table tbody');if(fleetBody){fleetBody.insertAdjacentHTML('beforeend',fleetRows.map(row=>`<tr data-row><td>${row[0]}</td><td>${row[1]}</td><td>${row[2]}</td><td>${row[3]}</td><td><span class="status ${row[5]}">${row[4]}</span></td></tr>`).join(''));}}
if(location.pathname.endsWith('/fleet.html')){document.querySelector('.table tbody')?.addEventListener('click',event=>{const row=event.target.closest('[data-row]');if(row){location.href=`truck-profile.html?truck=${encodeURIComponent(row.cells[0].textContent.trim())}`;}});document.querySelectorAll('.table tbody [data-row]').forEach(row=>{row.style.cursor='pointer';});}
if(location.pathname.endsWith('/truck-profile.html')){const truck=new URLSearchParams(location.search).get('truck');if(truck){const title=document.querySelector('.heading h2');if(title)title.textContent=truck;}}
if(location.pathname.endsWith('/trip-detail.html')){const trip=new URLSearchParams(location.search).get('trip');if(trip){const title=document.getElementById('tripTitle');if(title)title.textContent=`Trip ${trip}`;}}
if(location.pathname.endsWith('/advisor.html')){document.querySelectorAll('h3').forEach(title=>{if(title.textContent.trim()==='Voice F2 contract preview')title.closest('section.panel')?.remove();});}
if(location.pathname.endsWith('/calendar.html')){setTimeout(()=>{const heading=document.querySelector('main .heading');const months=document.querySelector('.calendar-two-months');if(!heading||!months)return;const selector=document.createElement('select');selector.innerHTML='<option value="1" selected>1 lună</option><option value="2">2 luni</option><option value="3">3 luni</option>';selector.style.cssText='padding:10px;border:1px solid var(--line);background:var(--panel);color:var(--teal-dark);font:700 11px Arial,sans-serif;margin-left:auto';months.querySelector('.panel-head').appendChild(selector);const third=document.createElement('section');third.className='panel';third.innerHTML='<div class="panel-head"><h3>Noiembrie 2026</h3><span>Month 3</span></div><div class="calendar-grid"><div class="day"><div class="day-head">Mon<strong>26</strong></div></div><div class="day"><div class="day-head">Tue<strong>27</strong></div><div class="event trip-0089"><strong>TR-0089</strong><small>Return / Arad</small></div></div><div class="day"><div class="day-head">Wed<strong>28</strong></div><div class="event trip-0089"><strong>TR-0089</strong><small>Closed</small></div></div><div class="day"><div class="day-head">Thu<strong>29</strong></div></div><div class="day"><div class="day-head">Fri<strong>30</strong></div><div class="event alert"><strong>TM-07</strong><small>Service</small></div></div><div class="day"><div class="day-head">Sat<strong>31</strong></div></div><div class="day"><div class="day-head">Sun<strong>1</strong></div></div></div>';months.appendChild(third);const panels=[...months.children];function setMonths(){const count=Number(selector.value);panels.forEach((panel,index)=>panel.hidden=index>=count);months.style.gridTemplateColumns=`repeat(${count},minmax(0,1fr))`;}selector.addEventListener('change',setMonths);setMonths();},0);}
if(location.pathname.endsWith('/calendar.html')){const style=document.createElement('style');style.textContent='.event.continues-start{margin-right:-8px;border-left:4px solid #477aa6;border-radius:6px 0 0 6px;position:relative;z-index:2}.event.continues-middle{margin-left:-8px;margin-right:-8px;padding-left:17px;border-left:0;border-radius:0;position:relative;z-index:2}.event.continues-end{margin-left:-8px;border-left:0;border-radius:0 6px 6px 0;position:relative;z-index:2}';document.head.appendChild(style);document.querySelectorAll('.trip-0088').forEach((event,index,array)=>event.classList.add(index===0?'continues-start':index===array.length-1?'continues-end':'continues-middle'));}
if(location.pathname.endsWith('/calendar.html')){const style=document.createElement('style');style.textContent='.calendar-two-months{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.calendar-two-months>.panel{margin:0}.calendar-two-months .calendar-grid{grid-template-columns:repeat(7,minmax(70px,1fr))}.calendar-two-months .day{min-height:150px}@media(max-width:900px){.calendar-two-months{grid-template-columns:1fr}}';document.head.appendChild(style);const stack=document.querySelector('main .stack');const calendarPanel=stack?.querySelector('.panel');if(stack&&calendarPanel){const monthPanel=document.createElement('section');monthPanel.className='panel';monthPanel.innerHTML='<div class="panel-head"><h3>October 2026</h3><span>Next month</span></div><div class="calendar-grid"><div class="day"><div class="day-head">Mon<strong>28</strong></div><div class="event trip-0090"><strong>TR-0090</strong><small>Delivery / Lyon</small></div></div><div class="day"><div class="day-head">Tue<strong>29</strong></div><div class="event trip-0090"><strong>TR-0090</strong><small>Delivery / Lyon</small></div></div><div class="day"><div class="day-head">Wed<strong>30</strong></div><div class="event trip-0090"><strong>TR-0090</strong><small>Return / Cluj</small></div></div><div class="day"><div class="day-head">Thu<strong>1</strong></div><div class="event trip-0089"><strong>TR-0089</strong><small>Delivery / Vienna</small></div></div><div class="day"><div class="day-head">Fri<strong>2</strong></div><div class="event trip-0089"><strong>TR-0089</strong><small>Return / Arad</small></div></div><div class="day"><div class="day-head">Sat<strong>3</strong></div></div><div class="day"><div class="day-head">Sun<strong>4</strong></div><div class="event alert"><strong>TM-07</strong><small>Service check</small></div></div></div><div class="legend"><span>Planned / active</span><span class="load">Loading / review</span><span class="alert">Conflict / service</span></div>';const months=document.createElement('div');months.className='calendar-two-months';calendarPanel.parentNode.insertBefore(months,calendarPanel);months.append(calendarPanel,monthPanel);const title=calendarPanel.querySelector('.panel-head h3');if(title)title.textContent='September 2026';}}
