document.querySelectorAll('[data-voice]').forEach(button=>button.addEventListener('click',()=>{button.textContent=button.textContent.includes('Start')?'Stop voice':'F2 / Start voice';button.classList.toggle('recording');}));
document.querySelectorAll('[data-filter]').forEach(input=>input.addEventListener('input',event=>{const query=event.target.value.toLowerCase();document.querySelectorAll('[data-row]').forEach(row=>{row.hidden=query&&!row.textContent.toLowerCase().includes(query);});}));
const orderPreviewPath=location.pathname.includes('/resources/')?'order-preview.html':'resources/order-preview.html';
const resourceNav=document.querySelector('.nav');
if(resourceNav&&!resourceNav.querySelector('a[href="bucket.html"]')){const bucketLink=document.createElement('a');bucketLink.href='bucket.html';bucketLink.innerHTML='<b>B</b><span>The Bucket List</span>';const fleetLink=resourceNav.querySelector('a[href="fleet.html"]');if(fleetLink)resourceNav.insertBefore(bucketLink,fleetLink);}
document.querySelectorAll('.opportunity').forEach(item=>{item.style.cursor='pointer';item.addEventListener('click',()=>{location.href=orderPreviewPath;});});
if(location.pathname.endsWith('/opportunities.html')){document.querySelectorAll('[data-row]').forEach(item=>{item.style.cursor='pointer';item.addEventListener('click',()=>{location.href='order-preview.html';});});}
if(location.pathname.endsWith('/fleet.html')){const fleetRows=[['TM-02 / Mercedes Actros','Andrei Marin','Vienna','94%','On route','warn'],['TM-04 / MAN TGX','Elena Stoica','Arad','89%','Ready',''],['TM-05 / Volvo FH','Radu Pavel','Cluj-Napoca','86%','Ready',''],['TM-06 / Scania S','Victor Dinu','Brno','77%','Loading','warn'],['TM-08 / Renault T','Sorin Matei','Budapest','81%','Ready',''],['TM-09 / Iveco S-Way','Adrian Neagu','Timisoara','68%','Inspection','warn'],['TM-10 / Volvo FM','Daniela Rusu','Frankfurt','92%','Ready','']];const fleetBody=document.querySelector('.table tbody');if(fleetBody){fleetBody.insertAdjacentHTML('beforeend',fleetRows.map(row=>`<tr data-row><td>${row[0]}</td><td>${row[1]}</td><td>${row[2]}</td><td>${row[3]}</td><td><span class="status ${row[5]}">${row[4]}</span></td></tr>`).join(''));}}
if(location.pathname.endsWith('/fleet.html')){document.querySelector('.table tbody')?.addEventListener('click',event=>{const row=event.target.closest('[data-row]');if(row){location.href=`truck-profile.html?truck=${encodeURIComponent(row.cells[0].textContent.trim())}`;}});document.querySelectorAll('.table tbody [data-row]').forEach(row=>{row.style.cursor='pointer';});}
if(location.pathname.endsWith('/truck-profile.html')){const truck=new URLSearchParams(location.search).get('truck');if(truck){const title=document.querySelector('.heading h2');if(title)title.textContent=truck;}}
